import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatCurrency, formatDate } from './formatters';

export async function exportToPDF(project, expenses, categories, categoryBreakdown) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(20);
  doc.setTextColor(33, 33, 33);
  doc.text('Ghar Kharcha', 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text('Construction Cost Report', 14, 27);

  // Project info
  doc.setFontSize(14);
  doc.setTextColor(33, 33, 33);
  doc.text(project.name, 14, 40);

  const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(`Total Spent: ${formatCurrency(totalSpent)}`, 14, 48);
  if (project.budget > 0) {
    doc.text(`Budget: ${formatCurrency(project.budget)}`, 14, 55);
    doc.text(`Remaining: ${formatCurrency(project.budget - totalSpent)}`, 14, 62);
  }
  doc.text(`Report Date: ${formatDate(new Date().toISOString())}`, 14, project.budget > 0 ? 69 : 55);
  doc.text(`Total Entries: ${expenses.length}`, 14, project.budget > 0 ? 76 : 62);

  // Category breakdown table
  let startY = project.budget > 0 ? 86 : 72;
  doc.setFontSize(13);
  doc.setTextColor(33, 33, 33);
  doc.text('Category Breakdown', 14, startY);

  const catRows = categoryBreakdown.map(item => [
    `${item.category.icon} ${item.category.name}`,
    item.count.toString(),
    formatCurrency(item.total),
    totalSpent > 0 ? `${((item.total / totalSpent) * 100).toFixed(1)}%` : '0%',
  ]);

  doc.autoTable({
    startY: startY + 4,
    head: [['Category', 'Entries', 'Amount', '% of Total']],
    body: catRows,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [45, 52, 54], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    columnStyles: {
      0: { cellWidth: 65 },
      2: { halign: 'right' },
      3: { halign: 'right' },
    },
  });

  // Expense details
  doc.addPage();
  doc.setFontSize(13);
  doc.setTextColor(33, 33, 33);
  doc.text('All Expenses', 14, 20);

  const sortedExpenses = [...expenses].sort((a, b) => new Date(b.date) - new Date(a.date));
  const expRows = sortedExpenses.map(e => {
    const cat = categories.find(c => c.id === e.categoryId);
    return [
      formatDate(e.date),
      cat ? `${cat.icon} ${cat.name}` : 'Unknown',
      e.note || '-',
      formatCurrency(e.amount),
    ];
  });

  doc.autoTable({
    startY: 26,
    head: [['Date', 'Category', 'Note', 'Amount']],
    body: expRows,
    styles: { fontSize: 8, cellPadding: 2.5 },
    headStyles: { fillColor: [45, 52, 54], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: 45 },
      3: { halign: 'right', cellWidth: 30 },
    },
  });

  // Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Ghar Kharcha App | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  doc.save(`${project.name.replace(/\s+/g, '_')}_Report.pdf`);
}
